/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaapp;

import academiaedjane.Alunos;
import academiaedjane.Funcionarios;
import javax.swing.JOptionPane;

/**
 *
 * @author 1282227687
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public CadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtenderecoFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelefoneFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsalarioFuncionario = new javax.swing.JTextField();
        txtfuncaoFuncionario = new javax.swing.JTextField();
        btcadastrarFuncionario = new javax.swing.JButton();
        jBtAlunos = new javax.swing.JButton();
        jBtconvidados = new javax.swing.JButton();
        jBtprofessores = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Santinho Developer");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 100));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 60, 51, 16);

        txtNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtNomeFuncionario);
        txtNomeFuncionario.setBounds(120, 80, 427, 30);

        txtenderecoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtenderecoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtenderecoFuncionario);
        txtenderecoFuncionario.setBounds(120, 140, 427, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("SALÁRIO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 230, 75, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("ENDEREÇO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 120, 83, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("TELEFONE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 180, 75, 16);

        txttelefoneFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txttelefoneFuncionario);
        txttelefoneFuncionario.setBounds(120, 200, 427, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("FUNÇÃO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 290, 65, 16);

        txtsalarioFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsalarioFuncionario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsalarioFuncionarioCaretUpdate(evt);
            }
        });
        getContentPane().add(txtsalarioFuncionario);
        txtsalarioFuncionario.setBounds(120, 250, 427, 30);

        txtfuncaoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtfuncaoFuncionario);
        txtfuncaoFuncionario.setBounds(120, 310, 427, 36);

        btcadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btcadastrarFuncionario.setText("♦ CADASTRAR FUNCIONARIO ♦");
        btcadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btcadastrarFuncionario);
        btcadastrarFuncionario.setBounds(320, 20, 230, 46);

        jBtAlunos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtAlunos.setText("Alunos");
        jBtAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtAlunos);
        jBtAlunos.setBounds(170, 380, 100, 23);

        jBtconvidados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtconvidados.setText("Convidados");
        jBtconvidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtconvidadosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtconvidados);
        jBtconvidados.setBounds(300, 380, 100, 23);

        jBtprofessores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtprofessores.setText("Professores");
        jBtprofessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtprofessoresActionPerformed(evt);
            }
        });
        getContentPane().add(jBtprofessores);
        jBtprofessores.setBounds(430, 380, 100, 23);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaapp/imagem/funcionarios.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 884, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenderecoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoFuncionarioActionPerformed

    private void btcadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarFuncionarioActionPerformed
        Funcionarios bdfuncionario = new Funcionarios();
        bdfuncionario.setEndereco_funcionario(txtenderecoFuncionario.getText());
        bdfuncionario.setNome_funcionario(txtNomeFuncionario.getText());
        bdfuncionario.setFuncao(txtfuncaoFuncionario.getText());
        bdfuncionario.setSalario_funcionario(txtsalarioFuncionario.getText());
        bdfuncionario.setTelefone_funcionario(txttelefoneFuncionario.getText());

        bdfuncionario.cadfuncionarios();

        txtNomeFuncionario.setText("");
        txtenderecoFuncionario.setText("");
        txtfuncaoFuncionario.setText("");
        txttelefoneFuncionario.setText("");
        txtsalarioFuncionario.setText("");

        JOptionPane.showMessageDialog(null, "Ok você já pode Cadastrar Mais");


    }//GEN-LAST:event_btcadastrarFuncionarioActionPerformed

    private void jBtAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlunosActionPerformed
        CadastrarAlunos cda = new CadastrarAlunos();
        cda.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtAlunosActionPerformed

    private void jBtconvidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtconvidadosActionPerformed
        CadastrarConvidado cdcv = new CadastrarConvidado();
        cdcv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtconvidadosActionPerformed

    private void jBtprofessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtprofessoresActionPerformed
        CadastrarProfessores cdpf = new CadastrarProfessores();
        cdpf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtprofessoresActionPerformed

    private void txtsalarioFuncionarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsalarioFuncionarioCaretUpdate
int sal = Integer.parseInt(txtsalarioFuncionario.getText());
if (sal < 0){

JOptionPane.showMessageDialog(null, "Um valor Negativo foi digitado \n "
                    + "Por Favor Redigite o Valor do Salário");
}
    }//GEN-LAST:event_txtsalarioFuncionarioCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastrarFuncionario;
    private javax.swing.JButton jBtAlunos;
    private javax.swing.JButton jBtconvidados;
    private javax.swing.JButton jBtprofessores;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtenderecoFuncionario;
    private javax.swing.JTextField txtfuncaoFuncionario;
    private javax.swing.JTextField txtsalarioFuncionario;
    private javax.swing.JTextField txttelefoneFuncionario;
    // End of variables declaration//GEN-END:variables
}
