/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaapp;

import academiaedjane.Alunos;
import academiaedjane.Professores;
import javax.swing.JOptionPane;

/**
 *
 * @author 1282227687
 */
public class CadastrarProfessores extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public CadastrarProfessores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_NomeProfessores = new javax.swing.JTextField();
        txt_EnderecoProfessores = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cpfprof = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_HorasTrabalhadasProfessores = new javax.swing.JTextField();
        txt_SalarioProfessores = new javax.swing.JTextField();
        btcadastrarProfessores = new javax.swing.JButton();
        txt_TelefoneProf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBtAlunos = new javax.swing.JButton();
        jBtconvidados = new javax.swing.JButton();
        jBtfuncionarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Santinho Developer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(600, 420));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 90, 16);
        getContentPane().add(txt_NomeProfessores);
        txt_NomeProfessores.setBounds(20, 50, 427, 30);

        txt_EnderecoProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EnderecoProfessoresActionPerformed(evt);
            }
        });
        getContentPane().add(txt_EnderecoProfessores);
        txt_EnderecoProfessores.setBounds(20, 100, 427, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("HORAS TRABALHADAS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 160, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("ENDEREÇO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 80, 100, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("TELEFONE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 100, 16);
        getContentPane().add(txt_cpfprof);
        txt_cpfprof.setBounds(250, 160, 190, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("SALÁRIO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 200, 70, 16);
        getContentPane().add(txt_HorasTrabalhadasProfessores);
        txt_HorasTrabalhadasProfessores.setBounds(20, 220, 190, 30);

        txt_SalarioProfessores.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_SalarioProfessoresCaretUpdate(evt);
            }
        });
        getContentPane().add(txt_SalarioProfessores);
        txt_SalarioProfessores.setBounds(250, 220, 190, 30);

        btcadastrarProfessores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btcadastrarProfessores.setText("♦ CADASTRAR PROFESSOR ♦");
        btcadastrarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarProfessoresActionPerformed(evt);
            }
        });
        getContentPane().add(btcadastrarProfessores);
        btcadastrarProfessores.setBounds(110, 280, 215, 40);
        getContentPane().add(txt_TelefoneProf);
        txt_TelefoneProf.setBounds(20, 160, 190, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 140, 40, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 160, 190, 30);

        jBtAlunos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtAlunos.setText("Alunos");
        jBtAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtAlunos);
        jBtAlunos.setBounds(440, 270, 110, 23);

        jBtconvidados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtconvidados.setText("Convidados");
        jBtconvidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtconvidadosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtconvidados);
        jBtconvidados.setBounds(440, 300, 110, 23);

        jBtfuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtfuncionarios.setText("Funcionários");
        jBtfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtfuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtfuncionarios);
        jBtfuncionarios.setBounds(440, 330, 110, 23);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 33)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaapp/imagem/PROFFITINESS.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 560, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EnderecoProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EnderecoProfessoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EnderecoProfessoresActionPerformed

    private void btcadastrarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarProfessoresActionPerformed
        Professores prof = new Professores();
        prof.setEndereçoProfessores(txt_EnderecoProfessores.getText());
        prof.setHoraTrabalhadasProfessores(txt_HorasTrabalhadasProfessores.getText());
        prof.setSalarioProfessores(txt_SalarioProfessores.getText());
        prof.setNomeProfessores(txt_NomeProfessores.getText());
        prof.setTelefoneProfessores(txt_TelefoneProf.getText());
        prof.setCpf(txt_cpfprof.getText());

        prof.cadProf();

        txt_EnderecoProfessores.setText("");
        txt_HorasTrabalhadasProfessores.setText("");
        txt_NomeProfessores.setText("");
        txt_SalarioProfessores.setText("");
        txt_cpfprof.setText("");
        txt_TelefoneProf.setText("");


    }//GEN-LAST:event_btcadastrarProfessoresActionPerformed

    private void jBtAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlunosActionPerformed
        CadastrarAlunos cda = new CadastrarAlunos();
        cda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtAlunosActionPerformed

    private void jBtconvidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtconvidadosActionPerformed
        CadastrarConvidado cdcv = new CadastrarConvidado();
        cdcv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtconvidadosActionPerformed

    private void jBtfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtfuncionariosActionPerformed
        CadastrarFuncionario cdf = new CadastrarFuncionario();
        this.dispose();
        cdf.setVisible(true);
    }//GEN-LAST:event_jBtfuncionariosActionPerformed

    private void txt_SalarioProfessoresCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_SalarioProfessoresCaretUpdate
int sal = Integer.parseInt(txt_SalarioProfessores.getText());
if (sal <0){

JOptionPane.showMessageDialog(null, "Um valor Negativo foi digitado \n "
                    + "Por Favor Redigite o Valor do Salário");
}
    }//GEN-LAST:event_txt_SalarioProfessoresCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProfessores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastrarProfessores;
    private javax.swing.JButton jBtAlunos;
    private javax.swing.JButton jBtconvidados;
    private javax.swing.JButton jBtfuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_EnderecoProfessores;
    private javax.swing.JTextField txt_HorasTrabalhadasProfessores;
    private javax.swing.JTextField txt_NomeProfessores;
    private javax.swing.JTextField txt_SalarioProfessores;
    private javax.swing.JTextField txt_TelefoneProf;
    private javax.swing.JTextField txt_cpfprof;
    // End of variables declaration//GEN-END:variables
}
