/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaapp;

import academiaedjane.Alunos;
import academiaedjane.Convidados;
import javax.swing.JOptionPane;

/**
 *
 * @author 1282227687
 */
public class CadastrarConvidado extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public CadastrarConvidado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnomeConvidado = new javax.swing.JTextField();
        txt_Cpf = new javax.swing.JLabel();
        txtcpfConvidado = new javax.swing.JTextField();
        txt_ValorPago = new javax.swing.JLabel();
        btCadastrarConvidado = new javax.swing.JButton();
        txtmensalidadeConvidado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBTalunos = new javax.swing.JButton();
        jBTfuncionarios = new javax.swing.JButton();
        jBTprofessores = new javax.swing.JButton();
        Academia = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Loki &Thor");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Loki &Thor");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Academia");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Academia");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SantinhoDeveloper");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(620, 430));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("NOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 60, 20);
        getContentPane().add(txtnomeConvidado);
        txtnomeConvidado.setBounds(20, 150, 330, 38);

        txt_Cpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_Cpf.setForeground(new java.awt.Color(255, 0, 255));
        txt_Cpf.setText("CPF");
        getContentPane().add(txt_Cpf);
        txt_Cpf.setBounds(20, 200, 120, 20);
        getContentPane().add(txtcpfConvidado);
        txtcpfConvidado.setBounds(20, 220, 330, 38);

        txt_ValorPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_ValorPago.setForeground(new java.awt.Color(255, 0, 255));
        txt_ValorPago.setText("VALOR A PAGAR:");
        getContentPane().add(txt_ValorPago);
        txt_ValorPago.setBounds(20, 260, 140, 16);

        btCadastrarConvidado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrarConvidado.setText("♦ CADASTRAR CONVIDADO ♦");
        btCadastrarConvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarConvidadoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarConvidado);
        btCadastrarConvidado.setBounds(140, 90, 210, 40);

        txtmensalidadeConvidado.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmensalidadeConvidadoCaretUpdate(evt);
            }
        });
        getContentPane().add(txtmensalidadeConvidado);
        txtmensalidadeConvidado.setBounds(20, 280, 330, 38);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("Loki &Thor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 10, 170, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Academia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 40, 80, 20);

        jBTalunos.setText("Alunos");
        jBTalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTalunosActionPerformed(evt);
            }
        });
        getContentPane().add(jBTalunos);
        jBTalunos.setBounds(480, 240, 110, 23);

        jBTfuncionarios.setText("Funcionários");
        jBTfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTfuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jBTfuncionarios);
        jBTfuncionarios.setBounds(480, 270, 110, 23);

        jBTprofessores.setText("Professores");
        jBTprofessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTprofessoresActionPerformed(evt);
            }
        });
        getContentPane().add(jBTprofessores);
        jBTprofessores.setBounds(480, 300, 110, 23);

        Academia.setForeground(new java.awt.Color(255, 0, 204));
        Academia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Academia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaapp/imagem/convidadosfit.png"))); // NOI18N
        Academia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Academia);
        Academia.setBounds(10, 10, 590, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarConvidadoActionPerformed

        Convidados bdconvidados = new Convidados();
        bdconvidados.setNome_convidado(txtnomeConvidado.getText());
        bdconvidados.setCpf_convidado(txtcpfConvidado.getText());
        bdconvidados.setValorApagar(txtmensalidadeConvidado.getText());

        bdconvidados.cadastrarCovidado();

        txtcpfConvidado.setText("");
        txtmensalidadeConvidado.setText(" ");
        txtnomeConvidado.setText("");
    }//GEN-LAST:event_btCadastrarConvidadoActionPerformed

    private void jBTalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTalunosActionPerformed
        CadastrarAlunos cda = new CadastrarAlunos();
        cda.setVisible(true);
        CadastrarConvidado.this.dispose();

    }//GEN-LAST:event_jBTalunosActionPerformed

    private void jBTfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTfuncionariosActionPerformed
        CadastrarFuncionario cdf = new CadastrarFuncionario();
        cdf.setVisible(true);
        CadastrarConvidado.this.dispose();

    }//GEN-LAST:event_jBTfuncionariosActionPerformed

    private void jBTprofessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTprofessoresActionPerformed
        CadastrarProfessores cdpf = new CadastrarProfessores();
        cdpf.setVisible(true);
        CadastrarConvidado.this.dispose();

    }//GEN-LAST:event_jBTprofessoresActionPerformed

    private void txtmensalidadeConvidadoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmensalidadeConvidadoCaretUpdate
        int mensalidade = Integer.parseInt(txtmensalidadeConvidado.getText());
        if (mensalidade < 0) {
            
            JOptionPane.showMessageDialog(null, "Um valor Negativo foi digitado \n "
                    + "Por Favor Redigite o Valor Pago");
        }
    }//GEN-LAST:event_txtmensalidadeConvidadoCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarConvidado().setVisible(true);
                new CadastrarConvidado().setSize(0, 0);
                new CadastrarConvidado().setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Academia;
    private javax.swing.JButton btCadastrarConvidado;
    private javax.swing.JButton jBTalunos;
    private javax.swing.JButton jBTfuncionarios;
    private javax.swing.JButton jBTprofessores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txt_Cpf;
    private javax.swing.JLabel txt_ValorPago;
    private javax.swing.JTextField txtcpfConvidado;
    private javax.swing.JTextField txtmensalidadeConvidado;
    private javax.swing.JTextField txtnomeConvidado;
    // End of variables declaration//GEN-END:variables
}
