//Santinho Developer
package telaapp;

import academiaedjane.Alunos;
import academiaedjane.AlunosTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import telaapp.telaPrincipal;

import javax.swing.JOptionPane;

//
public class CadastrarAlunos extends javax.swing.JFrame {

AlunosTableModel carregarTabela = new AlunosTableModel();

    public CadastrarAlunos() {
        initComponents();
        jTable_Alunos.setModel(carregarTabela);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txt_idade = new javax.swing.JTextField();
        txtmensalidade = new javax.swing.JTextField();
        txt_multa = new javax.swing.JTextField();
        btTelaFuncionario = new javax.swing.JButton();
        btCadastrarAluno1 = new javax.swing.JButton();
        btTelaconvidado = new javax.swing.JButton();
        btTelaprofessor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Alunos = new javax.swing.JTable();

        jLabel10.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel10AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SantinhoDeveloper");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(450, 100));
        setPreferredSize(new java.awt.Dimension(700, 550));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 60, 10);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("MULTA POR ATRASO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 420, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("IDADE:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 310, 80, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("ENDEREÇO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 110, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("TELEFONE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 100, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("PLANO MENSALIDADE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 360, 170, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Academia");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 50, 80, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("CPF:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 50, 30);

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Loki &Thor");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(490, 20, 150, 30);

        txtnome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtnome.setForeground(new java.awt.Color(0, 51, 255));
        txtnome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomeFocusGained(evt);
            }
        });
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome);
        txtnome.setBounds(20, 90, 369, 28);

        txtendereco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtendereco.setForeground(new java.awt.Color(0, 51, 255));
        txtendereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtendereco);
        txtendereco.setBounds(20, 150, 369, 28);

        txtcpf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcpf.setForeground(new java.awt.Color(0, 51, 255));
        txtcpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtcpf);
        txtcpf.setBounds(20, 210, 369, 28);

        txttelefone.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txttelefone.setForeground(new java.awt.Color(0, 51, 255));
        txttelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txttelefone);
        txttelefone.setBounds(20, 270, 369, 28);

        txt_idade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_idade.setForeground(new java.awt.Color(0, 51, 255));
        txt_idade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idade.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_idadeCaretUpdate(evt);
            }
        });
        txt_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idadeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idade);
        txt_idade.setBounds(20, 330, 369, 28);

        txtmensalidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtmensalidade.setForeground(new java.awt.Color(0, 51, 255));
        txtmensalidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmensalidade.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmensalidadeCaretUpdate(evt);
            }
        });
        getContentPane().add(txtmensalidade);
        txtmensalidade.setBounds(20, 380, 369, 28);

        txt_multa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_multa.setForeground(new java.awt.Color(0, 51, 255));
        txt_multa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_multa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_multaCaretUpdate(evt);
            }
        });
        getContentPane().add(txt_multa);
        txt_multa.setBounds(20, 440, 369, 28);

        btTelaFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTelaFuncionario.setText("FUNCIONÁRIOS");
        btTelaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btTelaFuncionario);
        btTelaFuncionario.setBounds(500, 340, 140, 30);

        btCadastrarAluno1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrarAluno1.setText("♦ CADASTRAR ALUNO ♦");
        btCadastrarAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarAluno1ActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarAluno1);
        btCadastrarAluno1.setBounds(210, 30, 179, 40);

        btTelaconvidado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTelaconvidado.setText("CONVIDADOS");
        btTelaconvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaconvidadoActionPerformed(evt);
            }
        });
        getContentPane().add(btTelaconvidado);
        btTelaconvidado.setBounds(500, 420, 140, 30);

        btTelaprofessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTelaprofessor.setText("PROFESSORES");
        btTelaprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaprofessorActionPerformed(evt);
            }
        });
        getContentPane().add(btTelaprofessor);
        btTelaprofessor.setBounds(500, 380, 140, 30);

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaapp/imagem/casal fitness.png"))); // NOI18N
        jLabel1.setText("CADASTRAR ALUNOS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 650, 470);

        jTable_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Alunos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 482, 640, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoActionPerformed

    private void btTelaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaFuncionarioActionPerformed
        CadastrarFuncionario cdf = new CadastrarFuncionario();

        CadastrarAlunos.this.dispose();
        cdf.setVisible(true);


    }//GEN-LAST:event_btTelaFuncionarioActionPerformed

    private void txt_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idadeActionPerformed
        int idade = Integer.parseInt(txt_idade.getText());
        if (idade < 10) {
            JOptionPane.showMessageDialog(null, "Aluno Muito Novo para \n"
                    + " ser bodybuilder desta academia volte após completar 10 anos");
        }

    }//GEN-LAST:event_txt_idadeActionPerformed

    private void jLabel10AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel10AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10AncestorAdded

    private void btCadastrarAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarAluno1ActionPerformed

        Alunos bdalunos = new Alunos();

        bdalunos.setNome_aluno(txtnome.getText());
        bdalunos.setCpf_aluno(txtcpf.getText());
        bdalunos.setIdade_aluno(txt_idade.getText());
        bdalunos.setMensalidade_aluno(txtmensalidade.getText());
        bdalunos.setEndereco_aluno(txtendereco.getText());
        bdalunos.setTelefone_aluno(txttelefone.getText());
        bdalunos.setMultraAtrazo_aluno(txt_multa.getText());

        bdalunos.cadastrarAluno();
        LimparCampoAluno();
        telaPrincipal tp = new telaPrincipal();
        tp.CarregarCampo("select * from alunos");

        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarAluno1ActionPerformed

    private void btTelaconvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaconvidadoActionPerformed
        CadastrarConvidado cdcv = new CadastrarConvidado();
        CadastrarAlunos.this.dispose();
        cdcv.setVisible(true);

    }//GEN-LAST:event_btTelaconvidadoActionPerformed
    public void validaAluno() {

        int idade = Integer.parseInt(txt_idade.getText());
        if (idade < 10) {
            JOptionPane.showMessageDialog(null, "Aluno Muito Novo para \n"
                    + " ser bodybuilder desta academia volte após completar 10 anos");

        } else {
            String idade2 = Integer.toString(idade);
            txt_idade.setText(idade2);

        }
    }

    private void LimparCampoAluno() {
        txtcpf.setText(" ");
        txt_idade.setText(" ");
        txtendereco.setText(" ");
        txtmensalidade.setText(" ");
        txtnome.setText(" ");
        txttelefone.setText(" ");
        txt_multa.setText("");
        txtnome.requestFocus();
    }
    private void btTelaprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaprofessorActionPerformed

        CadastrarProfessores cdp = new CadastrarProfessores();
        cdp.setVisible(true);
        CadastrarAlunos.this.dispose();

    }//GEN-LAST:event_btTelaprofessorActionPerformed

    private void txtnomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusGained

    }//GEN-LAST:event_txtnomeFocusGained

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txt_idadeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_idadeCaretUpdate
        int idade = Integer.parseInt(txt_idade.getText());
        if (idade == 9 || idade == 8 || idade == 7 || idade == 6 || idade == 5 || idade < 0) {
            JOptionPane.showMessageDialog(null, "Muito Novo para "
                    + "ser aluno desta academia \n volte após completar 10 anos\n"
                    + "Ou você Digitou uma Data Inválida");

        } else {
            String idade2 = Integer.toString(idade);
            txt_idade.setText(idade2);
        }
    }//GEN-LAST:event_txt_idadeCaretUpdate

    private void txtmensalidadeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmensalidadeCaretUpdate
        int ms = Integer.parseInt(txtmensalidade.getText());
        if (ms < 0) {

            JOptionPane.showMessageDialog(null, "Um valor Negativo foi digitado \n "
                    + "Por Redigite o Valor  da Mesalidade");

        }
    }//GEN-LAST:event_txtmensalidadeCaretUpdate

    private void txt_multaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_multaCaretUpdate
    int multa = Integer.parseInt(txt_multa.getText());
        if (multa < 0){
        
            JOptionPane.showMessageDialog(null, "Um valor Negativo foi digitado \n "
                    + "Por Favor Redigite o Valor  da Multa");
    
    
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_multaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAlunos().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarAluno1;
    private javax.swing.JButton btTelaFuncionario;
    private javax.swing.JButton btTelaconvidado;
    private javax.swing.JButton btTelaprofessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Alunos;
    private javax.swing.JTextField txt_idade;
    private javax.swing.JTextField txt_multa;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtmensalidade;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
