/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaapp;

import academiaedjane.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.AbstractTableModel;
//import sun.rmi.transport.Connection;

/**
 *
 * @author santo
 */
public class telaPrincipal extends javax.swing.JFrame {

    /* Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        CarregarCampo("select * from alunos;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBt_cadaluno = new javax.swing.JButton();
        jBt_cadprof = new javax.swing.JButton();
        jBt_cadfunc = new javax.swing.JButton();
        jBt_convi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Loki &Thor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 10, 500, 100);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Cpf", "Idade", "Mensalidade", "Multa", "Endereco", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 630, 1500, 200);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Academia");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 70, 170, 80);

        jButton1.setText("CARREGAR TABELA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 240, 180, 40);

        jBt_cadaluno.setBackground(new java.awt.Color(0, 102, 102));
        jBt_cadaluno.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jBt_cadaluno.setForeground(new java.awt.Color(255, 0, 204));
        jBt_cadaluno.setText("CAD_ALUNO");
        jBt_cadaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_cadalunoActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_cadaluno);
        jBt_cadaluno.setBounds(20, 100, 190, 60);

        jBt_cadprof.setBackground(new java.awt.Color(0, 102, 102));
        jBt_cadprof.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jBt_cadprof.setForeground(new java.awt.Color(255, 0, 204));
        jBt_cadprof.setText("CAD_PROFESSOR");
        jBt_cadprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_cadprofActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_cadprof);
        jBt_cadprof.setBounds(20, 170, 190, 60);

        jBt_cadfunc.setBackground(new java.awt.Color(0, 102, 102));
        jBt_cadfunc.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jBt_cadfunc.setForeground(new java.awt.Color(255, 0, 204));
        jBt_cadfunc.setText("CAD_FUNCIONARIO");
        jBt_cadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_cadfuncActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_cadfunc);
        jBt_cadfunc.setBounds(220, 170, 190, 60);

        jBt_convi.setBackground(new java.awt.Color(0, 102, 102));
        jBt_convi.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jBt_convi.setForeground(new java.awt.Color(255, 0, 204));
        jBt_convi.setText("CAD_CONVIDADO");
        jBt_convi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_conviActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_convi);
        jBt_convi.setBounds(220, 100, 190, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaapp/imagem/meninas fit.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 1500, 844);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBt_conviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_conviActionPerformed
        CadastrarConvidado cdc = new CadastrarConvidado();
        cdc.setVisible(true);

    }//GEN-LAST:event_jBt_conviActionPerformed

    private void jBt_cadalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_cadalunoActionPerformed
        CadastrarAlunos cda = new CadastrarAlunos();
        cda.setVisible(true);


    }//GEN-LAST:event_jBt_cadalunoActionPerformed

    private void jBt_cadprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_cadprofActionPerformed
        CadastrarProfessores cdp = new CadastrarProfessores();
        cdp.setVisible(true);

    }//GEN-LAST:event_jBt_cadprofActionPerformed

    private void jBt_cadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_cadfuncActionPerformed
        CadastrarFuncionario cdf = new CadastrarFuncionario();
        cdf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBt_cadfuncActionPerformed

    public void CarregarCampo(String SQL) {

        DefaultTableModel tbAlunos = (DefaultTableModel) jTable1.getModel();
        tbAlunos.setRowCount(0);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        

        try {
            Connection conn;
            conn = new Conexao().conectaBancoDados();
            PreparedStatement ps;
            ResultSet rs;
            String sql = "select * from alunos; ";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            

            while (rs.next()) {
                tbAlunos.addRow(new Object[]{
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),});

            }
            conn.close();
            ps.close();
            rs.close();

        } catch (Exception deupau) {
            JOptionPane.showMessageDialog(null, "Deu Erro no Carregar JTable \n" + deupau, "Chama Santinho", JOptionPane.ERROR);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_cadaluno;
    private javax.swing.JButton jBt_cadfunc;
    private javax.swing.JButton jBt_cadprof;
    private javax.swing.JButton jBt_convi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
